services:
  postgres:
    image: postgres:14
    container_name: maxit-postgres
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/initdb:/docker-entrypoint-initdb.d/

volumes:
  postgres_data:
